       DETALLE-SITUACION.
           SET SIT-INDEX TO 1
           SEARCH TAB-SITUACION-DETALLE
            WHEN TAB-CTAS-SITUACION(SIT-INDEX) = WK-SITUACION
             MOVE TAB-CTAS-SITUACION-DETALLE(SIT-INDEX)
             TO WK-DETALLE-SITUACION
           END-SEARCH.
       F-DETALLE-SITUACION.
