       DETALLE-APERTURA.
           SET APER-INDEX TO 1
           SEARCH TAB-APERTURA-DETALLE
            WHEN TAB-CTAS-APERTURA(APER-INDEX) = WK-APERTURA
             MOVE TAB-CTAS-APERTURA-DETALLE(APER-INDEX)
             TO WK-DETALLE-APERTURA
           END-SEARCH.
       F-DETALLE-APERTURA.
